### ISSUE TITLE
The service fails to broadcast the price feed when it's null on the chain

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-price-oracle#4]
Hey @xlab I found an issue with the price oracle.

If the price feed hasn't been submitted before on-chain and the service starts you end up with the error below. I submitted the price feed once with sdk-python using the same relayer address, it was submitted normally with no issues and then the price started broadcasting txs just fine and updating the feed.

I didn't even touch the docker container in the yaml file neither stop the process after broadcasting the tx from sdk-python. The moment the price feed was on the chain from sdk-python it started submitting txs normally.

<img width="2237" alt="image" src="https://user-images.githubusercontent.com/83584143/159454599-e960a069-a1f8-4e6b-928f-ba183932fda7.png">

> time="2022-03-22T09:51:57Z" level=error msg="failed to commit msg batch: null" error="4483E42CEB308CDC5A7C9B202E103F164FF1A4A54E4F1700CE310898561C696E: tx timed out" module=sdk-go size=1 svc=cosmosClient
> time="2022-03-22T09:51:57Z" level=error msg="failed to SyncBroadcastMsg" batch_size=1 error="4483E42CEB308CDC5A7C9B202E103F164FF1A4A54E4F1700CE310898561C696E: tx timed out" svc=oracle timeout=true
> time="2022-03-22T09:52:07Z" level=warning msg="metrics init failed, will retry in 1 min" error="statsd init failed: dial udp: lookup host.docker.internal: no such host"
> time="2022-03-22T09:52:15Z" level=info msg="PullPrice (pipeline run) done in 81.165393ms" dynamic=true provider=nftbank-estimates-v2 svc=oracle ticker=BAYC/WETH
> time="2022-03-22T09:52:57Z" level=error msg="failed to commit msg batch: null" error="4483E42CEB308CDC5A7C9B202E103F164FF1A4A54E4F1700CE310898561C696E: tx timed out" module=sdk-go size=1 svc=cosmosClient
> time="2022-03-22T09:52:57Z" level=error msg="failed to SyncBroadcastMsg" batch_size=1 error="4483E42CEB308CDC5A7C9B202E103F164FF1A4A54E4F1700CE310898561C696E: tx timed out" svc=oracle timeout=true
> time="2022-03-22T09:53:07Z" level=warning msg="metrics init failed, will retry in 1 min" error="statsd init failed: dial udp: lookup host.docker.internal: no such host"
> time="2022-03-22T09:53:15Z" level=info msg="PullPrice (pipeline run) done in 79.507951ms" dynamic=true provider=nftbank-estimates-v2 svc=oracle ticker=BAYC/WETH
> time="2022-03-22T09:53:18Z" level=error msg="set price Tx error: code: 11\ncodespace: sdk\ndata: \"\"\nevents:\n- attributes:\n  - index: false\n    key: YWNjX3NlcQ==\n    value: aW5qMWN5OHJwNGUyY3ptZjducnN6N2VrcWZmeXp0dnVkOXZ5cm5kem12LzA=\n  type: tx\n- attributes:\n  - index: false\n    key: c2lnbmF0dXJl\n    value: RmZzUG5TYWY3UGZ6ejh3QWVDUytnR01nVDlBbHJRWHhCYWh3OXVVdEMrWk9wQUxQM1h4anAyVFd5U3g0ODhaTkpkaDZvdEZ0V3FmTnhwb0pXL1lUdndBPQ==\n  type: tx\n- attributes:\n  - index: false\n    key: c3BlbmRlcg==\n    value: aW5qMWN5OHJwNGUyY3ptZjducnN6N2VrcWZmeXp0dnVkOXZ5cm5kem12\n  - index: false\n    key: YW1vdW50\n    value: NDQ2MDE1MDAwMDAwMDAwaW5q\n  type: coin_spent\n- attributes:\n  - index: false\n    key: cmVjZWl2ZXI=\n    value: aW5qMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsNnM1eWU5\n  - index: false\n    key: YW1vdW50\n    value: NDQ2MDE1MDAwMDAwMDAwaW5q\n  type: coin_received\n- attributes:\n  - index: false\n    key: cmVjaXBpZW50\n    value: aW5qMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsNnM1eWU5\n  - index: false\n    key: c2VuZGVy\n    value: aW5qMWN5OHJwNGUyY3ptZjducnN6N2VrcWZmeXp0dnVkOXZ5cm5kem12\n  - index: false\n    key: YW1vdW50\n    value: NDQ2MDE1MDAwMDAwMDAwaW5q\n  type: transfer\n- attributes:\n  - index: false\n    key: c2VuZGVy\n    value: aW5qMWN5OHJwNGUyY3ptZjducnN6N2VrcWZmeXp0dnVkOXZ5cm5kem12\n  type: message\n- attributes:\n  - index: false\n    key: ZmVl\n    value: NDQ2MDE1MDAwMDAwMDAwaW5q\n  type: tx\ngas_used: \"89739\"\ngas_wanted: \"89203\"\nheight: \"36905\"\ninfo: \"\"\nlogs: []\nraw_log: 'out of gas in location: Has; gasWanted: 89203, gasUsed: 89739: out of gas'\ntimestamp: \"\"\ntx: null\ntxhash: A52C6EC43D2F277CFA32AD8F9B5BA54D3F52A52ABC70CDB73F2F3155D7A85341\n" batch_size=1 err_code=11 hash=A52C6EC43D2F277CFA32AD8F9B5BA54D3F52A52ABC70CDB73F2F3155D7A85341 svc=oracle timeout=true
> time="2022-03-22T09:54:08Z" level=warning msg="metrics init failed, will retry in 1 min" error="statsd init failed: dial udp: lookup host.docker.internal: no such host"
> time="2022-03-22T09:54:15Z" level=info msg="PullPrice (pipeline run) done in 85.853405ms" dynamic=true provider=nftbank-estimates-v2 svc=oracle ticker=BAYC/WETH
> time="2022-03-22T09:54:18Z" level=info msg="sent Tx in 921.88306ms" batch_size=1 hash=95B3026EE52E4B0AFB73E0960E687638273233F032438C4930E9B4DED49CCA63 svc=oracle timeout=true
> time="2022-03-22T09:55:08Z" level=warning msg="metrics init failed, will retry in 1 min" error="statsd init failed: dial udp: lookup host.docker.internal: no such host"
> time="2022-03-22T09:55:15Z" level=info msg="PullPrice (pipeline run) done in 87.577109ms" dynamic=true provider=nftbank-estimates-v2 svc=oracle ticker=BAYC/WETH
> time="2022-03-22T09:55:19Z" level=info msg="sent Tx in 1.89983051s" batch_size=1 hash=C9F48D77C811E63BD7D6FC2CB3AEE646A32C91B0B99FB8033DE9B7962597CEAC svc=oracle timeout=true

**Comment by xlab** [comment]
@achilleas-kal I think this is a common pattern with all off-chain services, you can't submit anything to chain if the feed is not enabled, etc. The approach should be to ensure that feed exists, then enable it in the offchain sender.

If I am missing something, let me know. But what would be a desired behaviour? Just skipping the error and commit anyways?

**Comment by achilleas-kal** [comment]
Hey Max, the feed was enabled (given that you mean if the relayer address was authorized to submit the feed on-chain) but the oracle service is unable to submit the very first feed on-chain for the asset. Currently, the only way to use the oracle service is to use the injectived binary or sdk-python to submit the very first feed and only then, the service will start updating the feed.

Ideally the user shouldn't have to go through this trouble and if the address is authorized to submit a feed then the service should work even for the very first feed right?

**Comment by xlab** [comment]
@achilleas-kal can you please provide the example of sdk-go code for this part? I think the Go service formats first message incorrectly or something like that. Or, just send me a link to the "first working Tx" in the explorer. I could read the Tx contents and compare it with the output of price oracle.

**Comment by achilleas-kal** [comment]
@xlab sure, see: https://devnet.api.injective.dev/api/explorer/v1/txs/B2B6E8E8190BBF2AD78727D583603A09B62D2E9BFA629ED7DC6A8F2622EFD12E

That's the very first tx for the oracle asset sent from sdk-python.

Adding to a gist as well in case somebody nukes the devnet env: https://gist.github.com/achilleas-kal/dff8cda711e86dabc7e1880d6a828db7

And here's a tx sent by the go service (different asset): https://devnet.api.injective.dev/api/explorer/v1/txs/367111DBEB3343BED2606C7687421E98A0AECF7123B238D1525096951169DF48

https://gist.github.com/achilleas-kal/bc425ef1406fb82597a3f5dce8356803

Formatting is identical as far as I can tell

**Comment by achilleas-kal** [comment]
Just tested this in prod and it works! The price for the asset wasn't submitted on-chain before and didn't have the issue so closing here.
